### ISSUE TITLE
why error usage: id3.py [-h] [-t [TESTING]] [-d] [-r] 

### ISSUE THREAD

**Issue by mehdir32** [jayelm/decisiontrees#4]
parser = argparse.ArgumentParser()
parser.add_argument('training',type=argparse.FileType('r'),help='name of the')
parser.add_argument('-t','--testing',type=argparse.FileType('r'),nargs='?',const=None,default=False,help='name of the testing .csv file')
parser.add_argument('-d', '--decide', action='store_true',
                    help='enter decision REPL for the given tree')
parser.add_argument('-r', '--rules', action='store_true',
                    help='print out individual paths down the tree for'
                    'binary decisions')  # TODO: add CSV support

error:
usage: id3.py [-h] [-t [TESTING]] [-d] [-r] training
id3.py: error: the following arguments are required: training

**Comment by jayelm** [comment]
Hi Medhi, you need to supply a `training` file, e.g.

    python id3.py example_data/breast-cancer-training.csv

See the README for details, but this is very old code, so no guarantees, sorry!

**Comment by mehdir32** [comment]
Thankful
